INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
DEBUG:root:Doctor by id - 3 was not found
INFO:werkzeug:127.0.0.1 - - [27/Feb/2023 11:50:22] "[33mGET /doctor-api/3 HTTP/1.1[0m" 404 -
DEBUG:root:All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 937328179, testemail9@gmail.com)]
INFO:werkzeug:127.0.0.1 - - [27/Feb/2023 11:52:03] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:16:27,169 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-02-27 12:16:27,169 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2023-02-27 12:16:54,370 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 937328179, testemail9@gmail.com)]
2023-02-27 12:16:54,372 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:16:54] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:20:35,209 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-02-27 12:20:35,209 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2023-02-27 12:20:40,785 - root - DEBUG - Doctor by id - 2 was gotten, doctor: (Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com)
2023-02-27 12:20:40,786 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:20:40] "GET /doctor-api/2 HTTP/1.1" 200 -
2023-02-27 12:20:46,626 - root - DEBUG - Doctor by id - 1 was not found
2023-02-27 12:20:46,627 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:20:46] "[33mGET /doctor-api/1 HTTP/1.1[0m" 404 -
2023-02-27 12:21:04,447 - root - DEBUG - Doctor for delete by id - 7 was not found
2023-02-27 12:21:04,449 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:21:04] "[33mDELETE /doctor-api/7 HTTP/1.1[0m" 404 -
2023-02-27 12:22:01,346 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:22:01] "[31m[1mDELETE /doctor-api HTTP/1.1[0m" 405 -
2023-02-27 12:22:07,147 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 937328179, testemail9@gmail.com)]
2023-02-27 12:22:07,149 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:22:07] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:22:21,067 - root - DEBUG - Doctor by id - 24 was deleted
2023-02-27 12:22:21,068 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:22:21] "DELETE /doctor-api/24 HTTP/1.1" 200 -
2023-02-27 12:28:04,300 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-02-27 12:28:04,300 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2023-02-27 12:28:18,780 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com)]
2023-02-27 12:28:18,782 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:18] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:18,907 - root - DEBUG - New patient was added to DB: (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)
2023-02-27 12:28:18,913 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:18] "POST /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:18,918 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com), (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)]
2023-02-27 12:28:18,920 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:18] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:18,926 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com), (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)]
2023-02-27 12:28:18,927 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:18] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:18,949 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com), (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)]
2023-02-27 12:28:18,952 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:18] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:19,041 - root - DEBUG - Patient by id - 14 was deleted
2023-02-27 12:28:19,041 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:19] "DELETE /patient-api/14 HTTP/1.1" 200 -
2023-02-27 12:28:19,049 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com)]
2023-02-27 12:28:19,050 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:19] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:19,058 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com)]
2023-02-27 12:28:19,059 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:19] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:19,064 - root - DEBUG - Patient by id - 13 was gotten, patient: (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com)
2023-02-27 12:28:19,065 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:19] "GET /patient-api/13 HTTP/1.1" 200 -
2023-02-27 12:28:19,073 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2000, KindOfAche.MILD, 093778177, testemail7@gmail.com)]
2023-02-27 12:28:19,074 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:19] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:28:19,166 - root - DEBUG - Patient by id - 13 was updated, new patient: (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)
2023-02-27 12:28:19,167 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:28:19] "PUT /patient-api/13 HTTP/1.1" 200 -
2023-02-27 12:33:40,140 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)]
2023-02-27 12:33:40,142 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,216 - root - DEBUG - New patient was added to DB: (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)
2023-02-27 12:33:40,218 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "POST /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,222 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com), (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)]
2023-02-27 12:33:40,224 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,229 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com), (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)]
2023-02-27 12:33:40,230 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,238 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com), (Test Patient8, 2000, KindOfAche.MILD, 093778178, testemail8@gmail.com)]
2023-02-27 12:33:40,240 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,326 - root - DEBUG - Patient by id - 15 was deleted
2023-02-27 12:33:40,327 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "DELETE /patient-api/15 HTTP/1.1" 200 -
2023-02-27 12:33:40,335 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)]
2023-02-27 12:33:40,337 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,348 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)]
2023-02-27 12:33:40,349 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,355 - root - DEBUG - Patient by id - 13 was gotten, patient: (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)
2023-02-27 12:33:40,356 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api/13 HTTP/1.1" 200 -
2023-02-27 12:33:40,364 - root - DEBUG - All patients was gotten: [(Test Patient1, 2004, KindOfAche.MILD, 063778171, testemail1@gmail.com), (Test Patient2, 2000, KindOfAche.MILD, 093778172, testemail2@gmail.com), (Test Patient3, 2000, KindOfAche.MILD, 093778173, testemail3@gmail.com), (Test Patient4, 2000, KindOfAche.MILD, 093778174, testemail4@gmail.com), (Test Patient5, 2000, KindOfAche.MILD, 093778175, testemail5@gmail.com), (Test Patient6, 2000, KindOfAche.MILD, 093778176, testemail6@gmail.com), (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)]
2023-02-27 12:33:40,365 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "GET /patient-api HTTP/1.1" 200 -
2023-02-27 12:33:40,372 - root - DEBUG - Patient by id - 13 was updated, new patient: (Test Patient7, 2004, KindOfAche.MILD, 063778177, testemail7@gmail.com)
2023-02-27 12:33:40,372 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:40] "PUT /patient-api/13 HTTP/1.1" 200 -
2023-02-27 12:33:51,376 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com)]
2023-02-27 12:33:51,378 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,461 - root - DEBUG - New doctor was added to DB: (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)
2023-02-27 12:33:51,464 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "POST /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,468 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-27 12:33:51,469 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,473 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-27 12:33:51,475 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,480 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-27 12:33:51,482 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,586 - root - DEBUG - Doctor by id - 30 was deleted
2023-02-27 12:33:51,587 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "DELETE /doctor-api/30 HTTP/1.1" 200 -
2023-02-27 12:33:51,593 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com)]
2023-02-27 12:33:51,595 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,602 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com)]
2023-02-27 12:33:51,603 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,608 - root - DEBUG - Doctor by id - 23 was gotten, doctor: (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com)
2023-02-27 12:33:51,610 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api/23 HTTP/1.1" 200 -
2023-02-27 12:33:51,618 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 3, Specialty.ORTHOPEDIST, 937328178, testemail8@gmail.com)]
2023-02-27 12:33:51,620 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "GET /doctor-api HTTP/1.1" 200 -
2023-02-27 12:33:51,929 - root - DEBUG - Doctor by id - 23 was updated, new doctor: (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com)
2023-02-27 12:33:51,930 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 12:33:51] "PUT /doctor-api/23 HTTP/1.1" 200 -
2023-02-27 18:20:14,986 - root - DEBUG - Doctor for delete by id - 24 was not found
2023-02-27 18:20:15,000 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 18:20:15] "[33mDELETE /doctor-api/24 HTTP/1.1[0m" 404 -
2023-02-27 18:20:52,010 - root - DEBUG - Doctor by id - 24 was not found
2023-02-27 18:20:52,011 - werkzeug - INFO - 127.0.0.1 - - [27/Feb/2023 18:20:52] "[33mGET /doctor-api/24 HTTP/1.1[0m" 404 -
2023-02-27 18:22:46,858 - root - DEBUG - Doctor by id - 24 was not found
2023-02-28 09:27:07,261 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,341 - src - ERROR - Exception on /doctor-api [POST]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 40, in post
    doctor_service.add_doctors(doctor)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 12, in add_doctors
    db.session.add(doctor)
  File "<string>", line 2, in add
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,343 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,377 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,382 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,388 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,394 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,401 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,409 - src - ERROR - Exception on /patient-api [POST]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 41, in post
    patient_service.add_patient(patient)
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 12, in add_patient
    db.session.add(patient)
  File "<string>", line 2, in add
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,411 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,418 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,423 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,428 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:07,433 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:27:15,611 - src - ERROR - Exception on /doctor-api/24 [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 57, in get
    doctor = doctor_service.get_one_by_id(doctor_id)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 30, in get_one_by_id
    doctor = Doctor.query.get(doctor_id)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,709 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,712 - src - ERROR - Exception on /doctor-api [POST]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 40, in post
    doctor_service.add_doctors(doctor)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 12, in add_doctors
    db.session.add(doctor)
  File "<string>", line 2, in add
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,715 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,743 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,748 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,753 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,758 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,764 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,766 - src - ERROR - Exception on /patient-api [POST]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 41, in post
    patient_service.add_patient(patient)
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 12, in add_patient
    db.session.add(patient)
  File "<string>", line 2, in add
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,768 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,775 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,779 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,785 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8e300 (otid=0x7f5a07c73030) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:28:06,790 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f5a07c8dec0 (otid=0x7f5a07c72fa0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:32:13,340 - src - ERROR - Exception on /doctor-api/24 [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f7c51a55180 (otid=0x7f7c51a25cb0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 57, in get
    doctor = doctor_service.get_one_by_id(doctor_id)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 30, in get_one_by_id
    doctor = Doctor.query.get(doctor_id)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:32:13,344 - src - ERROR - Exception on /patient-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f7c51a55180 (otid=0x7f7c51a25cb0) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/patient_api.py", line 27, in get
    patients = patient_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/patient_service.py", line 21, in get_all
    return Patient.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:36:18,669 - src - ERROR - Exception on /doctor-api/24 [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fa17737ccc0 (otid=0x7fa17771ff00) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 57, in get
    doctor = doctor_service.get_one_by_id(doctor_id)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 30, in get_one_by_id
    doctor = Doctor.query.get(doctor_id)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:36:36,321 - src - ERROR - Exception on /doctor-api/24 [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fa17737ccc0 (otid=0x7fa17771ff00) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 57, in get
    doctor = doctor_service.get_one_by_id(doctor_id)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 30, in get_one_by_id
    doctor = Doctor.query.get(doctor_id)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:38:19,315 - src - ERROR - Exception on /doctor-api/24 [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fa17737ccc0 (otid=0x7fa17771ff00) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 57, in get
    doctor = doctor_service.get_one_by_id(doctor_id)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 30, in get_one_by_id
    doctor = Doctor.query.get(doctor_id)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:38:54,715 - src - ERROR - Exception on /doctor-api/24 [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fa17737ccc0 (otid=0x7fa17771ff00) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 57, in get
    doctor = doctor_service.get_one_by_id(doctor_id)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 30, in get_one_by_id
    doctor = Doctor.query.get(doctor_id)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 09:39:01,066 - root - DEBUG - Doctor by id - 24 was not found
2023-02-28 09:52:03,441 - root - DEBUG - Doctor by id - 24 was not found
2023-02-28 10:17:07,181 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:17:07,194 - src - ERROR - Exception on /doctor-api [POST]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 40, in post
    doctor_service.add_doctors(doctor)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 12, in add_doctors
    db.session.add(doctor)
  File "<string>", line 2, in add
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:17:07,207 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:19:40,278 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:19:53,526 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:19:53,532 - src - ERROR - Exception on /doctor-api [POST]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 40, in post
    doctor_service.add_doctors(doctor)
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 12, in add_doctors
    db.session.add(doctor)
  File "<string>", line 2, in add
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:19:53,537 - src - ERROR - Exception on /doctor-api [GET]
Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fb361380500 (otid=0x7fb36173fd50) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/denys/python/dentistClinic/src/rest/doctor_api.py", line 26, in get
    doctors = doctor_service.get_all()
  File "/home/denys/python/dentistClinic/src/service/doctor_service.py", line 21, in get_all
    return Doctor.query.all()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4274, in __call__
    return self.class_(**local_kw)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/denys/python/dentistClinic/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
2023-02-28 10:21:15,315 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com)]
2023-02-28 10:21:15,602 - root - DEBUG - New doctor was added to DB: (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)
2023-02-28 10:21:15,611 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-28 10:21:15,616 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-28 10:21:33,249 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-28 10:21:33,323 - root - DEBUG - New doctor was added to DB: (Test Doctor10, 3, Specialty.ORTHOPEDIST, 0937781710, testemail10@gmail.com)
2023-02-28 10:21:33,329 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com), (Test Doctor10, 3, Specialty.ORTHOPEDIST, 0937781710, testemail10@gmail.com)]
2023-02-28 10:21:33,333 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com), (Test Doctor10, 3, Specialty.ORTHOPEDIST, 0937781710, testemail10@gmail.com)]
2023-02-28 10:21:33,343 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com), (Test Doctor10, 3, Specialty.ORTHOPEDIST, 0937781710, testemail10@gmail.com)]
2023-02-28 10:21:33,499 - root - DEBUG - Doctor by id - 32 was deleted
2023-02-28 10:21:33,507 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-28 10:21:33,513 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-28 10:21:33,517 - root - DEBUG - Doctor by id - 31 was gotten, doctor: (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)
2023-02-28 10:21:33,525 - root - DEBUG - All doctors was gotten: [(Chak, 2, Specialty.ORTHOPEDIST, 682748592, email@gmail.com), (Derek, 4, Specialty.THERAPIST, 636582647, email2@gmail.com), (Rafael Piastry, 2, Specialty.THERAPIST, 675395625, rafael@gmail.com), (Test Doctor, 3, Specialty.ORTHOPEDIST, 937352817, testemail@gmail.com), (Test Doctor2, 3, Specialty.ORTHOPEDIST, 937328172, testemail2@gmail.com), (Test Doctor6, 3, Specialty.ORTHOPEDIST, 937328176, testemail6@gmail.com), (Test Doctor7, 3, Specialty.ORTHOPEDIST, 937328177, testemail7@gmail.com), (Test Doctor8, 4, Specialty.ORTHOPEDIST, 094728178, my_testemail8@gmail.com), (Test Doctor9, 3, Specialty.ORTHOPEDIST, 093778179, testemail9@gmail.com)]
2023-02-28 10:21:33,633 - root - DEBUG - Doctor by id - 31 was updated, new doctor: (Test Doctor9, 4, Specialty.ORTHOPEDIST, 094728179, my_testemail9@gmail.com)
